### ISSUE TITLE
Support for Nodejs10

### ISSUE THREAD

**Issue by cloudkite** [apex/up#769] opened 2019-05-29 04:41 UTC
## Prerequisites

* [x] I am running the latest version. (`up upgrade`)
* [x] I searched to see if the issue already exists.
* [x] I inspected the verbose debug output with the `-v, --verbose` flag.
* [x] Are you an Up Pro subscriber?

## Description

AWS just recently released support for nodejs v10 with a new runtime.
https://aws.amazon.com/about-aws/whats-new/2019/05/aws_lambda_adds_support_for_node_js_v10/

Was curious if this was already supported by changing the `runtime` parameter in `up.json`. While it seems that up correctly changes the lambda settings in AWS when hitting the server I get Internal Server errors and nothing in up logs  🤷🏻‍♀️

```
{
  ...
  "lambda": {
    "runtime": "nodejs10.x",
    "memory": 512
  }
}
```

**Comment by tj** [comment] 2019-05-29 10:08
still looking into the bug, I think it's a problem with the shim, the Node changes seem to break compatibility with the previous version, but I don't get any errors haha

**Comment by bfelbo** [comment] 2019-07-25 21:41
Any updates on this? :)

**Comment by tj** [comment] 2019-07-26 08:52
Nothing yet but I'll try to check it out this weekend, the lack of errors makes it a little awkward to diagnose haha, seems like Node is swallowing it somehow

**Comment by bfelbo** [comment] 2019-07-26 20:46
Haha, yeah, that sounds tough! Thanks!

**Comment by tj** [comment] 2019-07-27 11:04
Odd, I tried Node 10.x again and it seems fine just by changing the runtime, I'm not sure what the problem was before. Maybe I'll update the default to 10x as well, but `"runtime": "nodejs10.x"` should do the trick

**Comment by louisremi** [comment] 2019-08-01 15:06
@tj I confirm that I switched the runtime today to `nodejs10.x`, as I did just after the release was announced. This time there are no error. I guess the AWS team fixed a regression somewhere…

**Comment by tj** [comment] 2019-08-02 09:51
Interesting haha, I thought for sure it was something in the shim. I'll close this for now but I'll add some docs and maybe tweak the default if the backwards compatibility looks ok

**Closed by tj** 2019-08-02 09:51 UTC

**Comment by cloudkite** [comment] 2019-08-05 09:07
Finally got around to giving this another go, can confirm its working for me as well now. thanks for looking into it!
