### ISSUE TITLE
Minimal IAM Policy for deploying from CI

### ISSUE THREAD

**Issue by kevinsimper** [apex/up#666] opened 2018-05-21 23:22 UTC
What would be the minimal IAM Policy for deploying, I know the policy on the website, but that has also access to EC2 and is quite broad. For example I would not need to control a domain from there.

Like it would be a role that you could put on Travis-CI and not worry about them deleting your EC2 instances. 

I tried deleting everything other than Lambda, API Gateway and S3, but then I began to see that it access IAM during a deploy, couldn't it avoid that theoretically?

Would it only need access to Lambda and API Gateway?

**Comment by tj** [comment] 2018-05-22 17:09
I'll try and get this together soon! It's pretty generalized right now just to avoid forcing people to update it frequently but I'll try and tighten the requirements up, and a "deploy only" policy

**Comment by Prinzhorn** [comment] 2018-06-09 15:59
Might want to close this as a duplicate of #148

**Closed** 2023-05-26 11:08 UTC
Labels: Documentation
